# Generated by Django 5.2.2 on 2025-06-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
