# Generated by Django 5.2.2 on 2025-06-19 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
