# Generated by Django 5.2.2 on 2025-06-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_chef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='festivals',
        ),
        migrations.AddField(
            model_name='festival',
            name='recipes',
            field=models.ManyToManyField(related_name='festival_set', to='recipes.recipe'),
        ),
    ]
