# Generated by Django 5.2.2 on 2025-06-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_remove_recipe_festivals_festival_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='chef_photos/'),
        ),
    ]
