# Generated by Django 5.2.2 on 2025-07-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
