# Generated by Django 5.2.2 on 2025-07-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipe_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
    ]
