# Generated by Django 5.2.2 on 2025-07-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_remove_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='note',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
