# Generated by Django 5.2.2 on 2025-07-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_ingredient_note_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='note',
        ),
    ]
