# Generated by Django 5.2.2 on 2025-07-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_remove_ingredient_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='note',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
