# Generated by Django 5.2.2 on 2025-07-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='festival_set', to='recipes.recipe'),
        ),
        migrations.DeleteModel(
            name='Chef',
        ),
    ]
