# Generated by Django 5.2.2 on 2025-07-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_alter_festival_recipes_delete_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
